<Project Sdk="Microsoft.NET.Sdk">

	<Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />
	
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsAspireHost>true</IsAspireHost>
		<UserSecretsId>51ead2a4-da4c-424a-9c86-b7bf0f3435c6</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.AppHost" Version="13.0.0" />
		<PackageReference Include="Aspire.Hosting.SqlServer" Version="13.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CnabParser.Api\CnabParser.Api.csproj" />
	</ItemGroup>

</Project>
